brew install autojump
brew install icdiff
brew install neovim
brew install thefuck
brew install eddieantonio/eddieantonio/imgcat
brew install git-lfs
brew install cloc
brew install bat
brew install the_silver_searcher
brew install jq
brew install curl
